language: cpp

compiler:
  - clang
  - g++

script:
  - make
  - make rtags
  - ./rtags data/gumichan01-eastern_wind.flac data/gumichan01-eastern_wind.m4a data/gumichan01-eastern_wind.mp3 data/gumichan01-eastern_wind.ogg data/gumichan01-eastern_wind.opus data/gumichan01-eastern_wind.wav
